# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vu2_GGn23H0zonnIKAUfo2hHGWmihSrH
"""

streamlit
numpy
requests
pandas
matplotlib